import React from 'react';
import { 
  Receipt, User, Building2, Calendar, 
  ArrowRight, ShieldCheck, AlertTriangle, 
  Wallet, TrendingUp, Scale 
} from 'lucide-react';

/**
 * 👑 AYABUS VERIFY REFUND (Sovereign Edition)
 * ------------------------------------------------------------------
 * The Read-Only Forensic Ledger for Financial Payloads.
 * * * WORLD CLASS FEATURES:
 * 1. ZERO-TRUST DISPLAY: Extracts and displays the exact mathematical 
 * snapshot generated by the ReconciliationPhysics engine.
 * 2. VISUAL HIERARCHY: Clearly separates Customer Payout (Liability) 
 * from Platform Yield (Profit) and Operator Clawback (Debt).
 * 3. IMMUTABLE RECORD: Shows the exact ticket details tied to the math.
 */

const VerifyRefund = ({ data }) => {
  if (!data) return null;

  // ========================================================================
  // 1. DATA EXTRACTION & SAFETY MAPPING
  // ========================================================================
  // The 'data' prop here is the 'approvals' table row, which contains the 
  // joined ticket data and the mathematical payload snapshot.
  const ticket = data.ticket || {};
  const operatorName = ticket.partners?.company_name || 'Unknown Operator';
  const financials = data.payload_snapshot || {};

  // ========================================================================
  // 2. FORMATTERS
  // ========================================================================
  const formatMoney = (amount) => {
    return new Intl.NumberFormat('en-UG', { 
      style: 'currency', currency: 'UGX', maximumFractionDigits: 0 
    }).format(amount || 0);
  };

  const formatDate = (dateString) => {
    if (!dateString) return 'N/A';
    return new Date(dateString).toLocaleDateString('en-GB', {
      day: 'numeric', month: 'short', year: 'numeric'
    });
  };

  // Verify the math is flawless (Checksum validation for the L9 Admin)
  const mathCheck = 
    (financials.payout_customer_refund || 0) + 
    (financials.yield_platform_total || 0) + 
    (financials.yield_operator_compensation || 0);
    
  const isMathValid = Math.abs(mathCheck - (financials.original_total_paid || 0)) < 1;

  return (
    <div className="animate-in fade-in slide-in-from-bottom-4 duration-500 flex flex-col gap-6" style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      
      {/* ========================================================================
          SECTION A: THE TICKET IDENTITY (Who is this for?)
          ======================================================================== */}
      <section style={{ 
        background: 'var(--bg-canvas)', border: '1px solid var(--border-subtle)', 
        borderRadius: '12px', padding: '24px' 
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '11px', fontWeight: '800', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
             <Receipt size={14} /> Source Document
          </div>
          <div style={{ fontSize: '11px', fontFamily: 'monospace', color: 'var(--text-main)', background: 'var(--bg-surface)', padding: '4px 8px', borderRadius: '4px', border: '1px solid var(--border-subtle)', fontWeight: '700' }}>
            REF: {ticket.ticket_hash || 'UNKNOWN'}
          </div>
        </div>
        
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px' }}>
          {/* Passenger Identity */}
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: '12px' }}>
            <div style={{ padding: '10px', background: 'var(--bg-input)', borderRadius: '8px', color: 'var(--text-muted)' }}>
              <User size={20} />
            </div>
            <div>
              <div style={{ fontSize: '10px', fontWeight: '800', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: '2px' }}>Passenger</div>
              <div style={{ fontSize: '16px', fontWeight: '800', color: 'var(--text-main)' }}>{ticket.passenger_name || 'Anonymous'}</div>
              <div style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '4px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                <Calendar size={12} /> {formatDate(ticket.travel_date)} at {ticket.departure_time}
              </div>
            </div>
          </div>

          {/* Operator Identity */}
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: '12px' }}>
            <div style={{ padding: '10px', background: 'var(--bg-input)', borderRadius: '8px', color: 'var(--text-muted)' }}>
              <Building2 size={20} />
            </div>
            <div>
              <div style={{ fontSize: '10px', fontWeight: '800', color: 'var(--text-muted)', textTransform: 'uppercase', marginBottom: '2px' }}>Target Operator Vault</div>
              <div style={{ fontSize: '16px', fontWeight: '800', color: 'var(--text-main)' }}>{operatorName}</div>
              <div style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '4px' }}>
                Original Fare Paid: <span style={{ fontWeight: '700', color: 'var(--text-main)' }}>{formatMoney(financials.original_base_fare)}</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ========================================================================
          SECTION B: THE FORENSIC LEDGER (The Math)
          ======================================================================== */}
      <section style={{ 
        background: 'var(--bg-surface)', border: '1px solid var(--border-subtle)', 
        borderRadius: '12px', overflow: 'hidden' 
      }}>
        <div style={{ padding: '20px 24px', background: 'var(--bg-canvas)', borderBottom: '1px solid var(--border-subtle)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <h3 style={{ margin: 0, fontSize: '14px', fontWeight: '900', display: 'flex', alignItems: 'center', gap: '8px', color: 'var(--text-main)', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
            <Scale size={16} color="var(--brand-primary)" /> Financial Settlement Ledger
          </h3>
          
          {/* The Mathematical Sentinel */}
          {isMathValid ? (
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '10px', fontWeight: '800', color: 'var(--status-success)', background: 'rgba(16, 185, 129, 0.1)', padding: '4px 10px', borderRadius: '12px' }}>
              <ShieldCheck size={12} /> CHECKSUM VERIFIED
            </div>
          ) : (
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '10px', fontWeight: '800', color: 'var(--status-danger)', background: 'rgba(239, 68, 68, 0.1)', padding: '4px 10px', borderRadius: '12px', animation: 'pulse 2s infinite' }}>
              <AlertTriangle size={12} /> CHECKSUM FAILED
            </div>
          )}
        </div>

        <div style={{ padding: '24px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
          
          {/* 1. Original Receipt */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingBottom: '16px', borderBottom: '1px dashed var(--border-subtle)' }}>
            <div>
              <div style={{ fontSize: '12px', fontWeight: '800', color: 'var(--text-muted)', textTransform: 'uppercase' }}>Original Total Paid</div>
              <div style={{ fontSize: '11px', color: 'var(--text-muted)', marginTop: '2px' }}>Base Fare + Platform Tax</div>
            </div>
            <div style={{ fontSize: '16px', fontWeight: '800', color: 'var(--text-main)', fontFamily: 'monospace' }}>
              {formatMoney(financials.original_total_paid)}
            </div>
          </div>

          {/* 2. Customer Refund Liability */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '16px', background: 'var(--bg-canvas)', borderRadius: '8px', border: '1px solid var(--border-subtle)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
              <Wallet size={16} color="var(--status-danger)" />
              <div>
                <div style={{ fontSize: '13px', fontWeight: '800', color: 'var(--text-main)' }}>Customer Payout Queue</div>
                <div style={{ fontSize: '11px', color: 'var(--text-muted)', marginTop: '2px' }}>Funds to be returned to {ticket.passenger_name}</div>
              </div>
            </div>
            <div style={{ fontSize: '18px', fontWeight: '900', color: 'var(--status-danger)', fontFamily: 'monospace' }}>
              {formatMoney(financials.payout_customer_refund)}
            </div>
          </div>

          {/* 3. Platform Yield (Profit) */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '16px', background: 'var(--brand-primary-subtle)', borderRadius: '8px', border: '1px solid var(--brand-subtle)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
              <TrendingUp size={16} color="var(--brand-primary)" />
              <div>
                <div style={{ fontSize: '13px', fontWeight: '800', color: 'var(--brand-primary)' }}>AyaBus Platform Yield</div>
                <div style={{ fontSize: '11px', color: 'var(--brand-primary)', opacity: 0.8, marginTop: '2px' }}>Non-refundable Tax + Penalty Cut</div>
              </div>
            </div>
            <div style={{ fontSize: '18px', fontWeight: '900', color: 'var(--brand-primary)', fontFamily: 'monospace' }}>
              +{formatMoney(financials.yield_platform_total)}
            </div>
          </div>

          {/* 4. Operator Compensation */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '16px', background: 'rgba(16, 185, 129, 0.05)', borderRadius: '8px', border: '1px solid rgba(16, 185, 129, 0.2)' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
              <Building2 size={16} color="var(--status-success)" />
              <div>
                <div style={{ fontSize: '13px', fontWeight: '800', color: 'var(--status-success)' }}>Operator Compensation</div>
                <div style={{ fontSize: '11px', color: 'var(--text-muted)', marginTop: '2px' }}>Penalty split kept by {operatorName}</div>
              </div>
            </div>
            <div style={{ fontSize: '18px', fontWeight: '900', color: 'var(--status-success)', fontFamily: 'monospace' }}>
              +{formatMoney(financials.yield_operator_compensation)}
            </div>
          </div>

        </div>
      </section>

      {/* ========================================================================
          SECTION C: THE CLAWBACK TARGET
          ======================================================================== */}
      <section style={{ 
        background: 'rgba(239, 68, 68, 0.05)', border: '1px dashed rgba(239, 68, 68, 0.4)', 
        borderRadius: '12px', padding: '20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center'
      }}>
        <div>
          <div style={{ fontSize: '11px', fontWeight: '800', color: 'var(--status-danger)', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
            Impending Treasury Clawback
          </div>
          <div style={{ fontSize: '13px', color: 'var(--text-main)', marginTop: '4px', fontWeight: '600' }}>
            Debt to be automatically deducted from {operatorName}
          </div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <ArrowRight size={20} color="var(--status-danger)" style={{ opacity: 0.5 }} />
          <div style={{ fontSize: '28px', fontWeight: '900', color: 'var(--status-danger)', fontFamily: 'monospace', letterSpacing: '-1px' }}>
            -{formatMoney(financials.debt_operator_clawback)}
          </div>
        </div>
      </section>

    </div>
  );
};

export default VerifyRefund;